generate_image:
  name: "generate image"
  description: "Turn a prompt into an image"
  fields:
    config_entry:
      name: "Config Entry"
      description: "The config entry to use for this action"
      required: true
      selector:
        config_entry:
          integration: grok_conversation
    prompt:
      name: "Prompt"
      description: "The text to turn into an image"
      required: true
      selector:
        text:
          multiline: true
    size:
      name: "Size"
      description: "The size of the image to generate"
      required: false
      example: "1024x1024"
      default: "1024x1024"
      selector:
        select:
          options:
            - "1024x1024"
            - "1024x1792"
            - "1792x1024"
    quality:
      name: "Quality"
      description: "The quality of the image that will be generated"
      required: false
      example: "standard"
      default: "standard"
      selector:
        select:
          options:
            - "standard"
            - "hd"
    style:
      name: "Style"
      description: "The style of the generated image"
      required: false
      example: "vivid"
      default: "vivid"
      selector:
        select:
          options:
            - "vivid"
            - "natural"
generate_content:
  name: "generate content"
  description: "Turn a prompt into content saved to a file"
  fields:
    config_entry:
      name: "Config Entry"
      description: "The config entry to use for this action"
      required: true
      selector:
        config_entry:
          integration: openai_conversation
    prompt:
      name: "Prompt"
      description: "The text to turn into an image"
      required: true
      selector:
        text:
          multiline: true
      example: "Hello, how can I help you?"
    filenames:
      name: "Filenames"
      description: "The filenames for the generated content"
      selector:
        text:
          multiline: true
      example: |
        - /path/to/file1.txt
        - /path/to/file2.txt